# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Site Name
description: Generic Site description
gtm: GTM-XXXXXX
author:
  name: Author Namw
  email: bonjour@genericsite.ca

# Grunt handles images and assets.
exclude: ['images', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true
